# Generated by Django 4.0.2 on 2022-02-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_why'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('head', models.TextField(blank=True, max_length=500)),
                ('row1', models.TextField(blank=True, max_length=500)),
                ('row2', models.TextField(blank=True, max_length=500)),
                ('row3', models.TextField(blank=True, max_length=500)),
                ('bottom', models.TextField(blank=True, max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
