# Generated by Django 4.0.2 on 2022-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('head1', models.TextField(blank=True, max_length=300)),
                ('head2', models.TextField(blank=True, max_length=300)),
                ('row1', models.TextField(blank=True, max_length=300)),
                ('row2', models.TextField(blank=True, max_length=300)),
                ('row3', models.TextField(blank=True, max_length=300)),
                ('bottom', models.TextField(blank=True, max_length=300)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
