# Generated by Django 4.0.2 on 2022-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_video',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
