# Generated by Django 4.0.2 on 2022-02-14 11:50

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_about_head3_alter_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.Events.get_file_name),
        ),
    ]
