# Generated by Django 4.0.2 on 2022-02-14 13:32

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_events_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('speciality', models.TextField(blank=True, max_length=40)),
                ('photo', models.ImageField(blank=True, upload_to=main_page.models.Chefs.get_file_name)),
                ('twit', models.URLField(blank=True, max_length=800)),
                ('faceb', models.URLField(blank=True, max_length=800)),
                ('insta', models.URLField(blank=True, max_length=800)),
                ('linked', models.URLField(blank=True, max_length=800)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
