# Generated by Django 4.0.2 on 2022-02-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_contmail_contphone_remove_contactus_call_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=50, unique=True)),
                ('persons', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
