# Generated by Django 4.0.2 on 2022-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_testomonial_alter_userreservation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('rows', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
